test: add mypy type checking
googleapis/python-bigquery-magics pull request #26
Opened 2024-04-29 22:52 UTC by chelsea-lin

Fixes #13 🦕

2024-04-30 18:55 UTC, tswast requested changes

2024-04-30 18:55 UTC, tswast commented on noxfile.py
>  nox.options.sessions = [
This is a templated file. See: https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/noxfile.py.j2

Please update [owlbot.py](https://github.com/googleapis/python-bigquery-magics/blob/23d54cd6721e362974f0119534fad726dc9a9608/owlbot.py#L63-L80) with this customization and/or update the template linked above.

2024-06-27 22:16 UTC, tswast commented
Once owlbot is updated, please also add `py.typed` file to the `bigquery_magics` directory.

2025-03-29 21:58 UTC, Hassan222-ux commented on noxfile.py
>  nox.options.sessions = [
main_chelsealin_mypy

2026-03-02 15:02 UTC, chalmerlowe commented
**Migration Notice:** This library is moving to the [google-cloud-python](https://github.com/googleapis/google-cloud-python) monorepo soon.

We closed this PR due to inactivity to ensure a clean migration. Please re-open this work in the new monorepo once the migration is complete!

2026-03-02 15:02 UTC, closed without merging